[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "gaussian_splatting"
readme = "README.md"
dynamic = ["version"]
dependencies = [
  "matplotlib",
  "torch",
  "tensorboard",
  "numpy",
  "tqdm",
  "opencv-python",
  "click",
  "scikit-image",
  "plyfile",
  "pyyaml",
  "pycolmap",
  "pygame",
  "pydantic",
]

[project.scripts]
launch_gaussian_splatting_training = "gaussian_splatting.launch_training:main"
launch_gaussian_splatting_inference = "gaussian_splatting.launch_inference:main"
launch_gaussian_splatting_colmap = "gaussian_splatting.launch_colmap:main"

[tool.setuptools.dynamic]
version = {attr = "gaussian_splatting.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["gaussian_splatting"]

[tool.ruff]
indent-width = 4
line-length = 120

[tool.ruff.lint]
select = ["I", "E", "F", "W"]

[tool.ruff.lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "gaussian_splatting",
  "first-party",
  "local-folder"
]
