training_images_path: datasets/lego_low2/train
poses_json_path: datasets/lego_low2/poses_colmap.json
intrinsics_json_path: datasets/lego_low2/intrinsics.json
ply_path: datasets/lego_low2/gaussians.ply

# ply_path: output/lego/20260715_220311/checkpoints/checkpoint_final.ply
max_sh_degree: 3
scale: 1

trainer_config:
  epochs: 10
  learning_rates:
    lr_positions: 16e-5
    lr_opacities: 5e-2
    lr_scales: 5e-3
    lr_quaternions: 1e-3
    lr_sh_coeffs: 25e-4
  gradient_accumulation_steps: 8
  max_gaussians_per_step: 3000
  log_every_n_epochs: 5

output_folder: output/lego