training_images_path: datasets/lego/train
poses_json_path: datasets/lego/poses_colmap.json
intrinsics_json_path: datasets/lego/intrinsics.json
ply_path: datasets/lego/gaussians.ply
max_sh_degree: 1
scale: 1

renderer_config:
  focal_length: 200
  width: 600
  height: 400

trainer_config:
  epochs: 1000
  learning_rate: 1.0e-4
  gradient_accumulation_steps: 8
  max_gaussians_per_step: 3000
  log_every_n_epochs: 5

output_folder: output/lego